// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Jj_5uKFT2Zpr21Z-V2-dWQLKBg6u3qE',
    appId: '1:309250088866:web:9f5e634051e7b952449cfb',
    messagingSenderId: '309250088866',
    projectId: 'reddit-clone-c67e2',
    authDomain: 'reddit-clone-c67e2.firebaseapp.com',
    storageBucket: 'reddit-clone-c67e2.appspot.com',
    measurementId: 'G-EJKNT8MS2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCgh_P0Y12Xb_WaUJaP8lziUNnRfqT32M',
    appId: '1:309250088866:android:de138d67ca2a172b449cfb',
    messagingSenderId: '309250088866',
    projectId: 'reddit-clone-c67e2',
    storageBucket: 'reddit-clone-c67e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPMJRF0jmr_Rq4_agp36CimW_jQSr3sU',
    appId: '1:309250088866:ios:2ccfd1bff6b5737e449cfb',
    messagingSenderId: '309250088866',
    projectId: 'reddit-clone-c67e2',
    storageBucket: 'reddit-clone-c67e2.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPMJRF0jmr_Rq4_agp36CimW_jQSr3sU',
    appId: '1:309250088866:ios:5e55590978f8ae9b449cfb',
    messagingSenderId: '309250088866',
    projectId: 'reddit-clone-c67e2',
    storageBucket: 'reddit-clone-c67e2.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
